# Generated by Django 4.2.5 on 2023-09-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('qty', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Books',
                'verbose_name_plural': 'Bookss',
            },
        ),
    ]
